### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by ghost1372** [cnbluefire/CoolControls.WinUI3#1]
hi, I have recently become interested in using composition and Win2D, and I am collecting and creating new controls. The best resources I found were from you and a few others. I like to collect all of them in one package.
I wanted to get your permission to use your codes.

i added your github link to source codes i used.

https://github.com/WinUICommunity/WinUICommunity/tree/main/dev/Components.Win2d

tnx

**Comment by cnbluefire** [comment]
You can use it as you please. I'm glad my code has been helpful to you.
